## Database Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
#spring.datasource.username=havi
#spring.datasource.password=
#
#spring.datasource.hikari.maximum-pool-size = 50
#spring.datasource.hikari.connection-timeout = 30000
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/your_database_name}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:your_password}
server.port=${PORT:8080}

# Let Hibernate build the tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false